### PR TITLE
support "files" filed

### PR DESCRIPTION
**Pull request by azu**
This pull request add "files" filed support.

```sh
npe files "src/, lib/, bin/"
```

- https://docs.npmjs.com/files/package.json#files

### CODE REVIEW

**Comment by zeke** [comment]
Nice! Can you add a test for it?

**Comment by azu** [comment]
@zeke Yes! I've added tests.

**Comment by zeke** [comment]
💣

**Comment by zeke** [comment]
I just published 1.0.0, not because this was a breaking change but because I want to signal that this package is now following semver.

Thanks, @azu!

**Pull request merged**
